os: osx
language: minimal
osx_image: xcode11

addons:
  homebrew:
    packages:
    - berkeley-db4
    - boost
    - libevent
    - sqlcipher

install:
  - echo -e "machine gitlab.com\n  login bakaoh\n  password $GITLAB_AT" >~/.netrc
  - git clone https://gitlab.com/nunchuck/nunchuck-qt nunchuk-qt --depth 1 && cd nunchuk-qt

script:
  - echo "Test" > test.txt

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: test.txt
  on:
    tags: true
